config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, :controllers => { :registrations => "acme/registrations"}
  post 'verifications' => 'verifications#create'
  patch 'verifications' => 'verifications#verify'
  resources :users, only: [:show]
  resources :reminders, only: [:new, :create,:show, :edit, :update,:destroy]
  get 'verify_number' => 'users#verify_number'


  get 'schedule/index'
  post '/schedule' => 'schedule#index'
  post '/stations'=> 'schedule#stations'
  post '/lateness_by_station'=> 'schedule#lateness_by_station'



    # Rails.application.routes.draw do
  get 'schedule/index'

    #   devise_for :users, controllers: {
    #     sessions: 'sessions'
    #   }
    # end




  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reminders
  validate :phone_format
	# validates_uniqueness_of :mobile_number
  validates :mobile_number, phone: { possible: false, allow_blank: false, types: [:mobile] }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def needs_mobile_number_verifying?
    if is_verified
      return false
    end

    return true
  end

  def phone_format
    if mobile_number[0] != '1'
      mobile_number.insert(0, '1')
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		if user_signed_in?
			@user = current_user
			@reminders = @user.reminders
			if @user.is_verified

			else
				flash[:notice] = "PLEASE VERIFY YOUR PHONE NUMBER"
				redirect_to verify_number_path(@user)
			end
			@times=load_times
			@offsets=[1,5,10]
		else
			redirect_to :root
		end
	end

	def verify_number
		@user = current_user
	end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div id='show-page' class="show-page">
  
  <div class="col1">

    <div class="user-info card">
      <h2>My Information</h2>
      <div class="info-field">
        Email:
        <div class="user-info-field"><strong><%= @user.email %></strong></div>
      </div>
      <div class="info-field">
        Phone:
        <div class="user-info-field"><strong><%=number_to_phone(@user.mobile_number) %></strong></div>
      </div>
      <div class="info-field">
        <strong><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'button-class' %></strong>
      </div>
    </div>

    <div class="reminder-show card">
      <div class="reminder-header">
        <table>
          <tr>
            <td>
              <h2>My Reminders</h2>
            </td>
            <td>
              <%= link_to  new_reminder_path, :class => 'new-reminder' do%>
              <i id='new-reminder-btn' class="fa fa-plus-square fa-2x"></i>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <% if @reminders.count==0 %>
        <div class="no-reminders-msg">
          <span>You currently have no reminders</span><br>
          <span>Use the <i class="fa fa-plus-square"></i> above to add. </span>
        </div>
      <% end %>
      <% @reminders.each do |reminder| %>
      <div class="reminder-container">
        <div class="train-container">
          <%= reminder.trainno %>
        </div>
        <div class="time-container">
          <%= reminder.alarmtime.strftime('%I:%M %p') %><br>
        </div>
        <div class="schedule-container">
          <% reminder.days.split("").each do |i|  %>
          <%=get_day_short(i).capitalize%><br>
          <% end %>
        </div>
        <div class="button-container">
          <%= link_to edit_reminder_path(reminder), :class => 'edit-reminder', remote: true do%>
          <i class="fa fa-pencil-square-o "></i>
          <% end %>
          <%= link_to  reminder_path(reminder), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } do%>
          <i class="fa fa-times"></i>
          <% end %>
            <i class="fa fa-info-circle sched-btn" data-train=<%=reminder.trainno%>></i>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col2">
    <div id='schedule-form'>
    </div>
    <div id='new-reminder-form' class="new-reminder-form form reminder-form">
      <%= render 'shared/new' %>
    </div>
    <div id="edit-form-place"></div>
  </div>

</div>

app/views/users/verify_number.html.erb
<div class="verification-page">
<br><br>
<!-- displays user's number as they entered it while signing up -->
<div class="phone-number">
<h1><%= number_to_phone(@user.mobile_number) %></h1>
</div>
<!-- this should be the option to edit their number if they made a mistake -->
<div class="edit-number-button">
<%= link_to 'Edit Number', edit_user_registration_path(current_user) %>
</div>
 
<%= mobile_verification_button %>

<%= verify_mobile_number_form %>
</div>